server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-to-solace        
      auto-offset-reset: earliest
kafka:
  topic:
    employee-events: employee-topic